//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxareProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConductoresXtaxi
    {
        public long id { get; set; }
        public long idConductor { get; set; }
        public string placaTaxi { get; set; }
    
        public virtual Conductor Conductor { get; set; }
        public virtual Taxi Taxi { get; set; }
    }
}
