//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxareProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kilometraje
    {
        public long id { get; set; }
        public string placa { get; set; }
        public double kilometraje1 { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual Taxi Taxi { get; set; }
    }
}
