//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxareProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Licencia
    {
        public long Numero_pase { get; set; }
        public long id_conductor { get; set; }
        public int id_secretaria { get; set; }
        public string categoria { get; set; }
        public System.DateTime expedicon { get; set; }
        public System.DateTime vencimiento { get; set; }
    
        public virtual Conductor Conductor { get; set; }
        public virtual Secretarias_transito Secretarias_transito { get; set; }
    }
}
