//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxareProject
{
    using System;
    using System.Collections.Generic;

    public partial class SeguridadSocial
    {
        Controladores.ControladorConductores cc = new Controladores.ControladorConductores();
        public int id { get; set; }
        public long id_conductor { get; set; }
        public System.DateTime pago_anterior { get; set; }
        public System.DateTime pago_siguiente { get; set; }
        public double valor { get; set; }

        public virtual Conductor Conductor { get; set; }

        public override string ToString()
        {

            return "id:" + this.id + " Fecha:" + this.pago_siguiente.ToShortDateString();
        }
    }
}
