//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxareProject
{
    using System;
    using System.Collections.Generic;

    public partial class Soat : IComparable<Soat>
    {
        public int id { get; set; }
        public string numero { get; set; }
        public string placa_taxi { get; set; }
        public System.DateTime expedicion { get; set; }
        public System.DateTime expiracion { get; set; }
        public string valor { get; set; }

        public virtual Taxi Taxi { get; set; }

        public int CompareTo(Soat other)
        {
            if (this.expiracion > other.expiracion)
            {
                return 1;
            }
            if (this.expiracion < other.expiracion)
            {
                return -1;
            }
            else
            {

                return 0;
            }
        }
        public override string ToString()
        {
           
            return " Soat no. " + this.numero + "vence "+ this.expiracion.Date;

        }
    }
}

