//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxareProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_taxareEntities : DbContext
    {
        public db_taxareEntities()
            : base("name=db_taxareEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Conductor> Conductors { get; set; }
        public virtual DbSet<ConductoresXtaxi> ConductoresXtaxis { get; set; }
        public virtual DbSet<GastosVariable> GastosVariables { get; set; }
        public virtual DbSet<Kilometraje> Kilometrajes { get; set; }
        public virtual DbSet<Licencia> Licencias { get; set; }
        public virtual DbSet<Marca> Marcas { get; set; }
        public virtual DbSet<Produccion> Produccions { get; set; }
        public virtual DbSet<Responsabilidade> Responsabilidades { get; set; }
        public virtual DbSet<Secretarias_transito> Secretarias_transito { get; set; }
        public virtual DbSet<SeguridadSocial> SeguridadSocials { get; set; }
        public virtual DbSet<Soat> Soats { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Taxi> Taxis { get; set; }
        public virtual DbSet<Tecnomecanica> Tecnomecanicas { get; set; }
        public virtual DbSet<Toperacion> Toperacions { get; set; }
    }
}
