//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Datamodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conductor
    {
        public Conductor()
        {
            this.CambioAceites = new HashSet<CambioAceite>();
            this.ConductoresXtaxis = new HashSet<ConductoresXtaxi>();
            this.Licencias = new HashSet<Licencia>();
            this.SeguridadSocials = new HashSet<SeguridadSocial>();
            this.Turnos = new HashSet<Turno>();
        }
    
        public long id { get; set; }
        public string cedula { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string telefono { get; set; }
    
        public virtual ICollection<CambioAceite> CambioAceites { get; set; }
        public virtual ICollection<ConductoresXtaxi> ConductoresXtaxis { get; set; }
        public virtual ICollection<Licencia> Licencias { get; set; }
        public virtual ICollection<SeguridadSocial> SeguridadSocials { get; set; }
        public virtual ICollection<Turno> Turnos { get; set; }
    }
}
