//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Datamodel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class taxareEntities : DbContext
    {
        public taxareEntities()
            : base("name=taxareEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CambioAceite> CambioAceites { get; set; }
        public DbSet<Conductor> Conductors { get; set; }
        public DbSet<ConductoresXtaxi> ConductoresXtaxis { get; set; }
        public DbSet<Gasto_Inventario> Gasto_Inventario { get; set; }
        public DbSet<GastosVariable> GastosVariables { get; set; }
        public DbSet<Inventario> Inventarios { get; set; }
        public DbSet<Kilometraje> Kilometrajes { get; set; }
        public DbSet<Licencia> Licencias { get; set; }
        public DbSet<Marca> Marcas { get; set; }
        public DbSet<Produccion> Produccions { get; set; }
        public DbSet<Responsabilidade> Responsabilidades { get; set; }
        public DbSet<Secretarias_transito> Secretarias_transito { get; set; }
        public DbSet<SeguridadSocial> SeguridadSocials { get; set; }
        public DbSet<Soat> Soats { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Taxi> Taxis { get; set; }
        public DbSet<Tecnomecanica> Tecnomecanicas { get; set; }
        public DbSet<Toperacion> Toperacions { get; set; }
        public DbSet<Turno> Turnos { get; set; }
    }
}
