//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Datamodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Secretarias_transito
    {
        public Secretarias_transito()
        {
            this.Licencias = new HashSet<Licencia>();
            this.Taxis = new HashSet<Taxi>();
        }
    
        public int id { get; set; }
        public string localidad { get; set; }
    
        public virtual ICollection<Licencia> Licencias { get; set; }
        public virtual ICollection<Taxi> Taxis { get; set; }
    }
}
