//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Datamodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taxi
    {
        public Taxi()
        {
            this.CambioAceites = new HashSet<CambioAceite>();
            this.ConductoresXtaxis = new HashSet<ConductoresXtaxi>();
            this.Gasto_Inventario = new HashSet<Gasto_Inventario>();
            this.GastosVariables = new HashSet<GastosVariable>();
            this.Kilometrajes = new HashSet<Kilometraje>();
            this.Produccions = new HashSet<Produccion>();
            this.Responsabilidades = new HashSet<Responsabilidade>();
            this.Soats = new HashSet<Soat>();
            this.Tecnomecanicas = new HashSet<Tecnomecanica>();
            this.Toperacions = new HashSet<Toperacion>();
            this.Turnos = new HashSet<Turno>();
        }
    
        public string placa { get; set; }
        public int id_matricula { get; set; }
        public int id_transito { get; set; }
        public int id_marca { get; set; }
        public int modelo { get; set; }
        public int cilindraje { get; set; }
        public string empresa_alfiliadora { get; set; }
        public int avaluo { get; set; }
    
        public virtual ICollection<CambioAceite> CambioAceites { get; set; }
        public virtual ICollection<ConductoresXtaxi> ConductoresXtaxis { get; set; }
        public virtual ICollection<Gasto_Inventario> Gasto_Inventario { get; set; }
        public virtual ICollection<GastosVariable> GastosVariables { get; set; }
        public virtual ICollection<Kilometraje> Kilometrajes { get; set; }
        public virtual Marca Marca { get; set; }
        public virtual ICollection<Produccion> Produccions { get; set; }
        public virtual ICollection<Responsabilidade> Responsabilidades { get; set; }
        public virtual Secretarias_transito Secretarias_transito { get; set; }
        public virtual ICollection<Soat> Soats { get; set; }
        public virtual ICollection<Tecnomecanica> Tecnomecanicas { get; set; }
        public virtual ICollection<Toperacion> Toperacions { get; set; }
        public virtual ICollection<Turno> Turnos { get; set; }
    }
}
