//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Datamodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turno
    {
        public int id { get; set; }
        public string placaTaxi { get; set; }
        public Nullable<long> idConductor { get; set; }
        public Nullable<System.DateTime> inicio { get; set; }
        public Nullable<System.DateTime> fin { get; set; }
        public Nullable<double> monto { get; set; }
    
        public virtual Conductor Conductor { get; set; }
        public virtual Taxi Taxi { get; set; }
    }
}
