//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Broker
{
    using System;
    using System.Collections.Generic;
    
    public partial class CambioAceite
    {
        public int id { get; set; }
        public string placa_taxi { get; set; }
        public long id_conductor { get; set; }
        public int id_kilometraje { get; set; }
        public string tipoAceite { get; set; }
    
        public virtual Conductor Conductor { get; set; }
        public virtual Taxis Taxis { get; set; }

        public CambioAceite(string placa_taxi, long id_conductor, int id_kilometraje, string tipoAceite)
        {
            this.placa_taxi = placa_taxi;
            this.id_conductor = id_conductor;
            this.id_kilometraje = id_kilometraje;
            this.tipoAceite = tipoAceite;
        }

        public CambioAceite()
        {
        }
    }
}
