//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Broker
{
    using System;
    using System.Collections.Generic;
    
    public partial class CambioAceite
    {

        /// <summary>
        /// Metodo constructor
        /// </summary>
        /// <param name="placaTaxi"></param>
        /// <param name="idConductor"></param>
        /// <param name="tipoAceite"></param>
        /// <param name="taller"></param>
        /// <param name="fecha"></param>
        public CambioAceite(string placaTaxi, long idConductor, string tipoAceite, string taller, System.DateTime fecha)
        {

            this.placaTaxi = placaTaxi;
            this.idConductor = idConductor;
            this.tipoAceite = tipoAceite;
            this.taller = taller;
            this.fecha = fecha;
        }

        public int id { get; set; }
        public string placaTaxi { get; set; }
        public long idConductor { get; set; }
        public string tipoAceite { get; set; }
        public string taller { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual Conductor Conductor { get; set; }
        public virtual Taxis Taxis { get; set; }

       
    }
    
}
