//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Broker
{
    using System;
    using System.Collections.Generic;
    
    public partial class GastosFijos
    {
        /// <summary>
        /// Metodo constructor
        /// </summary>
        /// <param name="idGastofijo"></param>
        /// <param name="estaPago"></param>
        public GastosFijos(long idGastofijo, bool estaPago)
        {
            this.idGastofijo = idGastofijo;
            this.estaPago = estaPago;

        }
        public long id { get; set; }
        public long idGastofijo { get; set; }
        public bool estaPago { get; set; }
    }
}
