//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Broker
{
    using System;
    using System.Collections.Generic;
    
    public partial class GastosVariables
    {
        public GastosVariables(int id, string placa, string descripcion, DateTime fecha, double kilometraje, double valor)
        {
            this.id = id;
            this.placa = placa;
            this.descripcion = descripcion;
            this.fecha = fecha;
            this.kilometraje = kilometraje;
            this.valor = valor;
        }

        public int id { get; set; }
        public string placa { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha { get; set; }
        public double kilometraje { get; set; }
        public double valor { get; set; }
    
        public virtual Taxis Taxis { get; set; }
    }
}
