//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Broker
{
    using System;
    using System.Collections.Generic;
    
    public partial class GastoInventario
    {
        public long id { get; set; }
        public long idInventario { get; set; }
        public string placaTaxi { get; set; }
        public int cantidadUsada { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual Inventario Inventario { get; set; }
        public virtual Taxis Taxis { get; set; }
    }
}
