//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Broker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gasto_Inventario
    {
        public Gasto_Inventario(int id, int id_inventario, string placaTaxi, int cant_usada, DateTime fecha)
        {
            this.id = id;
            this.id_inventario = id_inventario;
            this.placaTaxi = placaTaxi;
            this.cant_usada = cant_usada;
            this.fecha = fecha;
        }

        public int id { get; set; }
        public int id_inventario { get; set; }
        public string placaTaxi { get; set; }
        public int cant_usada { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual Inventario Inventario { get; set; }
        public virtual Taxis Taxis { get; set; }
    }
}
