//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Broker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Licencias
    {
        public long Numero_pase { get; set; }
        public long id_conductor { get; set; }
        public int id_secretaria { get; set; }
        public string categoria { get; set; }
        public System.DateTime expedicon { get; set; }
        public System.DateTime vencimiento { get; set; }

        public Licencias(long numero_pase, long id_conductor, int id_secretaria, string categoria, DateTime expedicon, DateTime vencimiento)
        {
            Numero_pase = numero_pase;
            this.id_conductor = id_conductor;
            this.id_secretaria = id_secretaria;
            this.categoria = categoria;
            this.expedicon = expedicon;
            this.vencimiento = vencimiento;
        }

        public virtual Conductor Conductor { get; set; }
        public virtual Secretarias_transito Secretarias_transito { get; set; }
    }
}
