//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Broker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produccion
    {
        public long id { get; set; }
        public Nullable<long> idTurno { get; set; }
        public double producido { get; set; }
    
        public virtual Turnos Turnos { get; set; }

        public Produccion(long id, long idTurno, double producido)
        {
            this.id = id;
            this.idTurno = idTurno;
            this.producido = producido;


        }
    }
}
