//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Broker
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_taxareEntities : DbContext
    {
        public db_taxareEntities()
            : base("name=db_taxareEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CambioAceite> CambioAceite { get; set; }
        public virtual DbSet<Conductor> Conductor { get; set; }
        public virtual DbSet<ConductoresXtaxis> ConductoresXtaxis { get; set; }
        public virtual DbSet<GastoInventario> GastoInventario { get; set; }
        public virtual DbSet<GastosFijos> GastosFijos { get; set; }
        public virtual DbSet<GastosVariables> GastosVariables { get; set; }
        public virtual DbSet<Inventario> Inventario { get; set; }
        public virtual DbSet<Kilometrajes> Kilometrajes { get; set; }
        public virtual DbSet<Licencias> Licencias { get; set; }
        public virtual DbSet<Marcas> Marcas { get; set; }
        public virtual DbSet<Produccion> Produccion { get; set; }
        public virtual DbSet<Responsabilidades> Responsabilidades { get; set; }
        public virtual DbSet<Secretarias_transito> Secretarias_transito { get; set; }
        public virtual DbSet<SeguridadSocial> SeguridadSocial { get; set; }
        public virtual DbSet<Soat> Soat { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Taxis> Taxis { get; set; }
        public virtual DbSet<Tecnomecanica> Tecnomecanica { get; set; }
        public virtual DbSet<Toperacion> Toperacion { get; set; }
        public virtual DbSet<Turnos> Turnos { get; set; }
    }
}
