//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Broker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taxis : IComparable<Broker.Taxis>
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]


        public Taxis()
        {
            this.CambioAceite = new HashSet<CambioAceite>();
            this.ConductoresXtaxis = new HashSet<ConductoresXtaxis>();
            this.Gasto_Inventario = new HashSet<Gasto_Inventario>();
            this.GastosVariables = new HashSet<GastosVariables>();
            this.Kilometrajes = new HashSet<Kilometrajes>();
            this.Produccion = new HashSet<Produccion>();
            this.Responsabilidades = new HashSet<Responsabilidades>();
            this.Soat = new HashSet<Soat>();
            this.Tecnomecanica = new HashSet<Tecnomecanica>();
            this.Toperacion = new HashSet<Toperacion>();
            this.Turnos = new HashSet<Turnos>();
        }

        public Taxis(string placa, int id_matricula, int id_transito, int id_marca, int modelo, int cilindraje, string empresa_alfiliadora, int avaluo)
        {
            this.placa = placa;
            this.id_matricula = id_matricula;
            this.id_transito = id_transito;
            this.id_marca = id_marca;
            this.modelo = modelo;
            this.cilindraje = cilindraje;
            this.empresa_alfiliadora = empresa_alfiliadora;
            this.avaluo = avaluo;
        }

        public string placa { get; set; }
        public int id_matricula { get; set; }
        public int id_transito { get; set; }
        public int id_marca { get; set; }
        public int modelo { get; set; }
        public int cilindraje { get; set; }
        public string empresa_alfiliadora { get; set; }
        public int avaluo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CambioAceite> CambioAceite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConductoresXtaxis> ConductoresXtaxis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gasto_Inventario> Gasto_Inventario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GastosVariables> GastosVariables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kilometrajes> Kilometrajes { get; set; }
        public virtual Marcas Marcas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produccion> Produccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Responsabilidades> Responsabilidades { get; set; }
        public virtual Secretarias_transito Secretarias_transito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Soat> Soat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tecnomecanica> Tecnomecanica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Toperacion> Toperacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Turnos> Turnos { get; set; }

        
        public int CompareTo(Taxis other)
        {

            if (this.avaluo > other.avaluo)
            {
                return 1;
            }
            if (this.avaluo == other.avaluo)
            {
                return 0;
            }
            else
            {
                return -1;
            }
        }
    }
}
