//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Broker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turnos
    {
        public Turnos(int id, string placaTaxi, long? idConductor, DateTime? inicio, DateTime? fin, double? monto)
        {
            this.id = id;
            this.placaTaxi = placaTaxi;
            this.idConductor = idConductor;
            this.inicio = inicio;
            this.fin = fin;
            this.monto = monto;
        }

        public Turnos()
        {
        }

        public int id { get; set; }
        public string placaTaxi { get; set; }
        public Nullable<long> idConductor { get; set; }
        public Nullable<System.DateTime> inicio { get; set; }
        public Nullable<System.DateTime> fin { get; set; }
        public Nullable<double> monto { get; set; }
    
        public virtual Conductor Conductor { get; set; }
        public virtual Taxis Taxis { get; set; }
    }
}
